// Template definitions — these would come from the database in production.
// Variables, per-member flags, multi-doc flags, and sign-in-portal flags are
// all first-class so the UI can switch behavior off the data.

export const TEMPLATES = {
  "fast-track": {
    name: "Fast Track (Permanent Residence)",
    tplLabel: "Cyprus-FastTrack-PR v1",
    deadline: 60,
    variables: {
      minInvestment: { label: "Minimum investment", value: "\u20AC300,000", token: "{{minInvestment}}" },
      minIncome: { label: "Minimum annual income", value: "\u20AC50,000", token: "{{minIncome}}" },
      govFees: { label: "Government fees", value: "\u20AC500 submission + \u20AC70 / person registration", token: "{{govFees}}" },
      processingTime: { label: "Processing time", value: "2\u20136 months", token: "{{processingTime}}" },
      validity: { label: "Validity", value: "Lifetime", token: "{{validity}}" },
    },
    keyFacts: [
      { label: "Min. investment", value: "\u20AC300,000" },
      { label: "Min. income", value: "\u20AC50,000 / year (main applicant)" },
      { label: "Processing time", value: "2\u20136 months" },
      { label: "Validity", value: "Lifetime" },
      { label: "Gov. fees", value: "\u20AC500 submission + \u20AC70 registration / person" },
    ],
    documents: [
      { id: "d1", name: "Valid passport", desc: "Original + certified copies \u00B7 collected separately per family member", required: true, collectPer: "familyMember" },
      { id: "d2", name: "Proof of investment", desc: "Title deed / sale agreement (DLS) / share certificates + payment receipts", required: true },
      { id: "d3", name: "Proof of fund transfer from abroad", desc: "Bank transfer with SWIFT confirmation \u00B7 supports multiple transactions (down payment, milestones, final)", required: true, multiDoc: true, minDocs: 1 },
      { id: "d4", name: "Proof of annual income", desc: "Tax return declarations or accountant\u2019s letter \u00B7 min. {{minIncome}}/year", required: true },
      { id: "d5", name: "Criminal record certificate", desc: "Apostilled \u00B7 country of origin + country of residence", required: true },
      { id: "d6", name: "Health insurance certificate", desc: "Covering applicant and dependants \u00B7 ~\u20AC200/person/year", required: true },
      { id: "d7", name: "Declaration of no employment intent", desc: "Signed in-portal by main applicant \u2014 no upload required", required: true, signInPortal: true },
      { id: "d8", name: "Proof of accommodation", desc: "Only if investment is non-residential (Categories B, C, or D) \u00B7 conditional", required: false, conditional: "non-residential investment" },
      { id: "d9", name: "Marriage certificate", desc: "Apostilled and translated \u00B7 only if including spouse \u00B7 conditional", required: false, conditional: "spouse included" },
      { id: "d10", name: "Birth certificates", desc: "Apostilled and translated \u00B7 only if including children under 18 \u00B7 conditional", required: false, conditional: "children under 18 included" },
      { id: "d11", name: "Student enrolment confirmation", desc: "Letter from institution + proof of financial dependency \u00B7 only for dependent child 18\u201325 \u00B7 conditional", required: false, conditional: "dependent child 18\u201325 included" },
    ],
    questions: [
      { id: "q1", text: "Investment category", type: "Dropdown \u00B7 A Residential / B Land / C Commercial / D Shares & Bonds", required: true, answerPer: "application" },
      { id: "q2", text: "Total investment amount (\u20AC)", type: "Number \u00B7 min. {{minInvestment}}", required: true, answerPer: "application" },
      { id: "q3", text: "Annual income from abroad (\u20AC)", type: "Number \u00B7 min. {{minIncome}}", required: true, answerPer: "application" },
      { id: "q4", text: "Country of origin and current residence", type: "Short text \u00B7 answered separately by each family member", required: true, answerPer: "familyMember" },
      { id: "q5", text: "Include spouse?", type: "Yes / No", required: true, answerPer: "application" },
      { id: "q6", text: "Children under 18 to include", type: "Number", required: false, answerPer: "application" },
      { id: "q7", text: "Dependent child aged 18\u201325 (student) to include?", type: "Yes / No \u00B7 conditional", required: false, answerPer: "application" },
      { id: "q8", text: "Has this person ever been refused entry to Cyprus or any EU country?", type: "Yes / No + explanation \u00B7 answered separately by each family member", required: true, answerPer: "familyMember" },
    ],
  },
  "pink-slip": {
    name: "Pink Slip (Temporary Residence Permit)",
    tplLabel: "Cyprus-PinkSlip-temp v1",
    deadline: 45,
    variables: {
      minIncome: { label: "Minimum annual income", value: "\u20AC24,000", token: "{{minIncome}}" },
      minDeposit: { label: "Minimum Cyprus bank deposit", value: "\u20AC10,000", token: "{{minDeposit}}" },
      govFees: { label: "Government fees", value: "\u20AC70\u2013\u20AC140 per person", token: "{{govFees}}" },
      processingTime: { label: "Processing time", value: "4\u20138 months", token: "{{processingTime}}" },
      validity: { label: "Validity", value: "1 year, renewable annually", token: "{{validity}}" },
    },
    keyFacts: [
      { label: "Min. income", value: "\u20AC24,000 / year (single applicant)" },
      { label: "Bank deposit", value: "\u20AC10,000 in a Cyprus bank (transferred from abroad)" },
      { label: "Processing time", value: "4\u20138 months" },
      { label: "Validity", value: "1 year, renewable annually" },
      { label: "Gov. fees", value: "\u20AC70\u2013\u20AC140 per person" },
    ],
    documents: [
      { id: "d1", name: "Application form MVIS8", desc: "Signed in-portal by the applicant \u2014 no upload required", required: true, signInPortal: true },
      { id: "d2", name: "Valid passport", desc: "Original + copies \u00B7 collected separately per family member", required: true, collectPer: "familyMember" },
      { id: "d3", name: "Proof of accommodation", desc: "12-month rental agreement (Mukhtar certified + Tax Office stamp) or title deed", required: true },
      { id: "d4", name: "Cyprus bank statements + SWIFT confirmations", desc: "Showing min. {{minIncome}}/year transferred from abroad \u00B7 multiple transactions supported", required: true, multiDoc: true, minDocs: 1 },
      { id: "d5", name: "Proof of income from abroad", desc: "Salary slips, pension records, or dividend statements", required: true },
      { id: "d6", name: "Health insurance certificate", desc: "Private insurance \u00B7 ~\u20AC200/person/year", required: true },
      { id: "d7", name: "Bank guarantee", desc: "Refundable \u00B7 first application only \u00B7 some nationalities exempt \u00B7 conditional", required: false, conditional: "first application" },
      { id: "d8", name: "Medical examination", desc: "HIV, Hepatitis B/C, syphilis, chest X-ray \u00B7 first application only \u00B7 conditional", required: false, conditional: "first application" },
      { id: "d9", name: "Police clearance certificate", desc: "Issued within last 6 months, apostilled \u00B7 first application only \u00B7 conditional", required: false, conditional: "first application" },
      { id: "d10", name: "Marriage certificate", desc: "Apostilled and translated \u00B7 only if including spouse \u00B7 conditional", required: false, conditional: "spouse included" },
      { id: "d11", name: "Birth certificates", desc: "Apostilled and translated \u00B7 only if including children \u00B7 conditional", required: false, conditional: "children included" },
    ],
    questions: [
      { id: "q1", text: "Is this a first application or renewal?", type: "Dropdown \u00B7 First / Renewal", required: true, answerPer: "application" },
      { id: "q2", text: "Annual income from abroad (\u20AC)", type: "Number \u00B7 min. {{minIncome}}", required: true, answerPer: "application" },
      { id: "q3", text: "Cyprus bank deposit amount (\u20AC)", type: "Number \u00B7 min. {{minDeposit}}", required: true, answerPer: "application" },
      { id: "q4", text: "Accommodation type", type: "Dropdown \u00B7 Rental / Owned", required: true, answerPer: "application" },
      { id: "q5", text: "Nationality", type: "Short text \u00B7 used to check bank-guarantee exemption", required: true, answerPer: "familyMember" },
      { id: "q6", text: "Include spouse?", type: "Yes / No", required: true, answerPer: "application" },
      { id: "q7", text: "Children to include", type: "Number", required: false, answerPer: "application" },
    ],
  },
};
